In [1]:
import pandas as pd

file_path = 'updatedDay.csv'
data = pd.read_csv(file_path)

In [2]:
data

,http_n-pc0,n_http,workhourhttp_n-pc0,n_workhourhttp,allact_n-pc0,n_allact,http_mean_url_depth,http_otherf_n-pc0,http_n_otherf,O,...,workhourhttp_leakf_n-pc0,email_n-pc2,workhourhttp_n_leakf,afterhourfile_n_exef,workhouremail_n-pc2,workhourhttp_n-pc2,http_jobf_n-pc2,http_socnetf_n-pc2,workhourhttp_socnetf_n-pc2,insider
0,29,29,28,28,34,34,3.000000,28,28,43,...,0,0,0,0,0,0,0,0,0,0
1,29,29,29,29,35,35,3.000000,25,25,42,...,0,0,0,0,0,0,0,0,0,0
2,29,29,28,28,34,34,3.000000,29,29,25,...,0,0,0,0,0,0,0,0,0,0
3,30,30,30,30,36,36,3.000000,30,30,37,...,0,0,0,0,0,0,0,0,0,0
4,29,29,29,29,34,34,3.000000,29,29,15,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
330440,162,162,162,162,181,181,3.000000,160,160,35,...,0,0,0,0,0,0,0,0,0,0
330441,29,29,21,21,34,34,3.000000,29,29,13,...,0,0,0,0,0,0,0,0,0,0
330442,10,10,9,9,13,13,3.000000,10,10,33,...,0,0,0,0,0,0,0,0,0,0
330443,114,114,114,114,127,129,2.578947,100,100,19,...,0,0,0,0,0,0,0,0,0,0
330444,162,162,162,162,187,187,3.000000,145,145,43,...,0,0,0,0,0,0,0,0,0,0

In [3]:
X = data.iloc[:, :-1]
y = data.iloc[:, -1]

In [4]:
X

,http_n-pc0,n_http,workhourhttp_n-pc0,n_workhourhttp,allact_n-pc0,n_allact,http_mean_url_depth,http_otherf_n-pc0,http_n_otherf,O,...,workhourfile_txtf_n-pc2,workhourhttp_leakf_n-pc0,email_n-pc2,workhourhttp_n_leakf,afterhourfile_n_exef,workhouremail_n-pc2,workhourhttp_n-pc2,http_jobf_n-pc2,http_socnetf_n-pc2,workhourhttp_socnetf_n-pc2
0,29,29,28,28,34,34,3.000000,28,28,43,...,0,0,0,0,0,0,0,0,0,0
1,29,29,29,29,35,35,3.000000,25,25,42,...,0,0,0,0,0,0,0,0,0,0
2,29,29,28,28,34,34,3.000000,29,29,25,...,0,0,0,0,0,0,0,0,0,0
3,30,30,30,30,36,36,3.000000,30,30,37,...,0,0,0,0,0,0,0,0,0,0
4,29,29,29,29,34,34,3.000000,29,29,15,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
330440,162,162,162,162,181,181,3.000000,160,160,35,...,0,0,0,0,0,0,0,0,0,0
330441,29,29,21,21,34,34,3.000000,29,29,13,...,0,0,0,0,0,0,0,0,0,0
330442,10,10,9,9,13,13,3.000000,10,10,33,...,0,0,0,0,0,0,0,0,0,0
330443,114,114,114,114,127,129,2.578947,100,100,19,...,0,0,0,0,0,0,0,0,0,0
330444,162,162,162,162,187,187,3.000000,145,145,43,...,0,0,0,0,0,0,0,0,0,0

In [5]:
y.value_counts()

insider
0    329479
2       861
1        85
3        20
Name: count, dtype: int64

In [6]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

In [7]:
X_train

,http_n-pc0,n_http,workhourhttp_n-pc0,n_workhourhttp,allact_n-pc0,n_allact,http_mean_url_depth,http_otherf_n-pc0,http_n_otherf,O,...,workhourfile_txtf_n-pc2,workhourhttp_leakf_n-pc0,email_n-pc2,workhourhttp_n_leakf,afterhourfile_n_exef,workhouremail_n-pc2,workhourhttp_n-pc2,http_jobf_n-pc2,http_socnetf_n-pc2,workhourhttp_socnetf_n-pc2
125816,29,29,25,25,34,34,3.000000,26,26,45,...,0,0,0,0,0,0,0,0,0,0
258687,95,95,89,89,108,108,3.000000,87,87,16,...,0,0,0,0,0,0,0,0,0,0
227465,29,29,29,29,42,42,3.000000,28,28,36,...,0,0,0,0,0,0,0,0,0,0
251781,95,95,95,95,106,106,3.000000,87,87,40,...,0,0,0,0,0,0,0,0,0,0
23193,95,95,79,79,106,106,3.000000,93,93,13,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
119879,162,162,162,162,179,179,3.000000,158,158,36,...,0,0,0,0,0,0,0,0,0,0
259178,95,95,95,95,107,109,2.536842,77,77,23,...,0,0,0,0,0,0,0,0,0,0
131932,114,114,109,109,127,127,2.903509,112,112,39,...,0,0,0,0,0,0,0,0,0,0
146867,114,114,114,114,125,129,3.000000,99,99,36,...,0,0,0,0,0,0,0,0,0,0
121958,95,95,95,95,106,108,3.000000,93,93,36,...,0,0,0,0,0,0,0,0,0,0

In [8]:
y_train.value_counts()

insider
0    230641
2       595
1        60
3        15
Name: count, dtype: int64

In [9]:
normal_indices = y_train[y_train == 0].index
malicious_indices = y_train[y_train != 0].index

normal_indices_sampled_10 = normal_indices[:int(len(normal_indices) * 0.1)]
normal_indices_sampled_20 = normal_indices[:int(len(normal_indices) * 0.2)]
normal_indices_sampled_50 = normal_indices[:int(len(normal_indices) * 0.5)]

sampled_indices_10 = normal_indices_sampled_10.append(malicious_indices)
sampled_indices_20 = normal_indices_sampled_20.append(malicious_indices)
sampled_indices_50 = normal_indices_sampled_50.append(malicious_indices)

X_train_sampled_10 = X_train.loc[sampled_indices_10]
y_train_sampled_10 = y_train.loc[sampled_indices_10]

X_train_sampled_20 = X_train.loc[sampled_indices_20]
y_train_sampled_20 = y_train.loc[sampled_indices_20]

X_train_sampled_50 = X_train.loc[sampled_indices_50]
y_train_sampled_50 = y_train.loc[sampled_indices_50]

In [10]:
y_train_sampled_10.value_counts()

insider
0    23064
2      595
1       60
3       15
Name: count, dtype: int64

In [11]:
normal_test_count = sum(y_test == 0)
malicious_test_count = sum(y_test != 0)

normal_indices_test = y_test[y_test == 0].index[:malicious_test_count]
malicious_indices_test = y_test[y_test != 0].index

balanced_indices_test = normal_indices_test.append(malicious_indices_test)

X_test_balanced = X_test.loc[balanced_indices_test]
y_test_balanced = y_test.loc[balanced_indices_test]

In [12]:
y_test_balanced.value_counts()

insider
0    296
2    266
1     25
3      5
Name: count, dtype: int64

In [13]:
y_test.value_counts()

insider
0    98838
2      266
1       25
3        5
Name: count, dtype: int64

In [14]:
import os

train_sampled_10 = pd.concat([X_train_sampled_10, y_train_sampled_10], axis=1)
train_sampled_20 = pd.concat([X_train_sampled_20, y_train_sampled_20], axis=1)
train_sampled_50 = pd.concat([X_train_sampled_50, y_train_sampled_50], axis=1)
test_balanced = pd.concat([X_test_balanced, y_test_balanced], axis=1)

folder_name = "sampled_data_dr/day"
if not os.path.exists(folder_name):
    os.makedirs(folder_name)

train_sampled_10.to_csv(os.path.join(folder_name, 'train_10.csv'), index=False)
train_sampled_20.to_csv(os.path.join(folder_name, 'train_20.csv'), index=False)
train_sampled_50.to_csv(os.path.join(folder_name, 'train_50.csv'), index=False)
test_balanced.to_csv(os.path.join(folder_name, 'test.csv'), index=False)